version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm --prefix apps/test-app-1/ install
      - npm --prefix apps/test-app-2/ install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - apps/test-app-1/**/*
    - apps/test-app-2/**/*
    - Procfile
    - .ebextensions/*.config
    - .ebextensions/scripts/*.sh
  discard-paths: no
